### ISSUE TITLE
consider removing println statements

### ISSUE THREAD

**Issue by yogthos** [GriffinScribe-LLC/clojure-aes#2]
The library shouldn't be doing its own printing as seen in [cipher](https://github.com/GriffinScribe-LLC/clojure-aes/blob/main/src/clojure_aes/encrypt/cipher_core.clj) function. If printing is needed for debugging then it would be best to allow passing a flag to enable the behaviour explicitly. It would also be best to use [clojure.tools.logging](https://github.com/clojure/tools.logging) interface for this which would then use the logger set up in the application instead of printing to standard out.

**Comment by CambodianCoder** [comment]
Agreed. Both of those points actually are on my list of improvements for this repo.

**Comment by CambodianCoder** [comment]
Printing from this library now only occur if a verbose flag "-v" is passed in. See latest from jar file "0.1.5" in targets directory.

Pull request welcome for clojure.tools.logging.
